### ISSUE TITLE
Does it work to compile with a Ubuntu 16.04 live USB?

### ISSUE THREAD

**Issue by i2000s** [Aorimn/dislocker#125]
I tried using a Ubuntu 16.04.2 Live USB to mount my broken Surface Pro 3 with Dislocker, but there was an error when I was compiling dislocker.

```
ubuntu-gnome@ubuntu-gnome:~/dislocker$ cmake .
PolarSSL/mbedTLS version: 2.6.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu-gnome/dislocker
ubuntu-gnome@ubuntu-gnome:~/dislocker$ make 
[ 78%] Built target dislocker
[ 81%] Linking C executable dislocker-metadata
libdislocker.so.0.7.1: undefined reference to `mbedtls_sha256'
libdislocker.so.0.7.1: undefined reference to `mbedtls_aes_setkey_dec'
libdislocker.so.0.7.1: undefined reference to `mbedtls_aes_crypt_ecb'
libdislocker.so.0.7.1: undefined reference to `mbedtls_aes_setkey_enc'
libdislocker.so.0.7.1: undefined reference to `mbedtls_aes_crypt_cbc'
collect2: error: ld returned 1 exit status
src/CMakeFiles/dislocker-metadata.dir/build.make:95: recipe for target 'src/dislocker-metadata' failed
make[2]: *** [src/dislocker-metadata] Error 1
CMakeFiles/Makefile2:128: recipe for target 'src/CMakeFiles/dislocker-metadata.dir/all' failed
make[1]: *** [src/CMakeFiles/dislocker-metadata.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
Noticed that the code above was done when the latest `mbedtls` was installed (v2.6.0). I indeed have tried the v2.0.0 with the patch. Both gave the same error. It also failed with `-fPIC` switch when compiling `mbedtls`. Any idea?

**Comment by i2000s** [comment]
Never mind, I made it work using the `universe` repo from APT source for `libmbedtls-dev` (version 2.2.1) without using the patch. I'll close this issue for now.
